[project]
name = "agentic-workflows"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-cloud-aiplatform>=2.3.0",
    "google-cloud-bigquery>=3.46.1",
    "google-cloud-storage>=3.16.0",
]

[project.scripts]
agentic-workflows = "agentic_workflows:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
